### ISSUE TITLE
Web interface, submit dropped file 500 Error

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1274]
Hi , 
when submitting a dropped file from the web interface i get the following 500 error, but Web console reports the following

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./submission/views.py", line 276, in submit_dropped
    "options": emit_options(task.options),
  File "./submission/views.py", line 88, in render_index
    return render_template(request, "submission/index.html", **values)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/bin/utils.py", line 81, in render_template
    return render(request, template_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: submission/index.html
2017-02-04 13:23:29,420 [django.request] ERROR: Internal Server Error: /submit/26415/dropped/259fb0c8397ec6bb7515a237bc551b38996ce328/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./submission/views.py", line 276, in submit_dropped
    "options": emit_options(task.options),
  File "./submission/views.py", line 88, in render_index
    return render_template(request, "submission/index.html", **values)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/bin/utils.py", line 81, in render_template
    return render(request, template_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: submission/index.html

**Comment by SparkyNZL** [comment]
anyone else having this issue with this ? its the package version with the flash as web interface :)

**Comment by jbremer** [comment]
Sorry for delay, I'll check it out ;-) Thanks again.

**Comment by SparkyNZL** [comment]
@jbremer Cheers :) It seems to be with any re-submit from the Web interface.

**Comment by jbremer** [comment]
@SparkyNZL This issue has been resolved and will be pushed shortly, after we finish off on some other features ;-)

**Comment by SparkyNZL** [comment]
awesome thanks guys :)

**Comment by SparkyNZL** [comment]
Can we have this added to the package please I updated today but its still not working, I also have what is probably a newbie question, but i think i need to ask it, With the package, the .conf files are not updated which is great, but what happens when more options are added eg, I run moloch over non-SSL and i see in the latest .git file the changes are included, but i dont think they have been on the Package version, am i correct? or am i talking rubbish ? 

@jbremer did you find out if that guy still had access to the flattr account

**Comment by jbremer** [comment]
Configuration files are updated in `package`. In fact, there's a whole bunch of configuration migration code that's able to upgrade your configuration all the way from Cuckoo 0.4 (if there's anyone still using that) up until the latest version of package.
All of the changes applied to `master` are also merged into `package` (at some point).
And no, but I'll contact him directly instead of through Github.

**Comment by SparkyNZL** [comment]
I think we can close this off :)

**Comment by craigdods** [comment]
Running into this today - what version was this corrected in?

**Comment by jbremer** [comment]
The above is for `2.0-rc2` or older, so any of the Python package (`pip install ...`) releases should do.

**Comment by craigdods** [comment]
Hmm, I'm on 2.0.3, guess I'll open a new bug

**Comment by jbremer** [comment]
Please do, thanks!
