### ISSUE TITLE
 Unable to shut 'cuckoo1' down or find the machine

### ISSUE THREAD

**Issue by tehfcae** [cuckoosandbox/cuckoo#1347]
I am getting the following error:

2017-03-20 17:17:28,407 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-03-20 17:18:35,549 [root] CRITICAL: CuckooCriticalError: Please update your configuration. Unable to shut 'cuckoo1' down or find the machine in its proper state: Timeout hit while for machine cuckoo1 to change status

My configuration files all point to cuckoo1 on vboxnet which I have created in virtual box. Any ideas as to what may be causing this issue?

**Comment by tehfcae** [comment]
The issue I ran into was that I was running cuckoo.py as sudo due to a permissions issue.

I fixed the permissions issue and stopped running cuckoo as sudo and worked.

**Comment by KZEE07** [comment]
Can you give more details regarding this issue pls! because am running into the issue and I honestly don't know whats wrong exactly! I tried to re-install it several times but still gets the same issue every time. what permissions did you change exactly !?  am running version 2.0.3
====================
2017-08-12 16:43:35,008 [cuckoo.machinery.virtualbox] DEBUG: _Stopping vm cuckoo1
CuckooCriticalError: Please update your configuration. Unable to shut 'cuckoo1' down or find the machine in its proper state: The virtual machine 'cuckoo1' doesn't exist! Please create one or more Cuckoo analysis VMs and properly fill out the Cuckoo configuration!_
