### ISSUE TITLE
IE (not responding) 

### ISSUE THREAD

**Issue by b1g334** [cuckoosandbox/cuckoo#841]
Hello,

14.04LTS
Cuckoo 2.1 rc1
Virtualbox
Win7 X64
IE 10.0.9200.16438

I'm just trying to fire a non-malicious URL to verify that everything is working ok.
./submit.py -o suspend=false --url http://www.cnn.com --package ie

But when I do, IE is (not responding)
I modified the base image and installed process explorer, and it shows that the IE process is suspended?

![image](https://cloud.githubusercontent.com/assets/18269162/14265766/4751017a-fa78-11e5-8016-208334f844d1.png)

When I start the image manually, net access is good. (vboxnet0, host only adapter)

I have set route to internet and internet to eth0 in cuckoo.conf. (this is on a separate network, i'll start working on the VPN functionality once i've confirmed I can get this to work.

**Comment by jbremer** [comment]
Hey :)

Unfortunately IE10 is currently not officially supported, although support for it would be a good step forward. If it's of interest - you could try IE8 which I know operates correctly.

Jurriaan

**Comment by b1g334** [comment]
I tried IE 10 out of desperation, as it was doing the same with 8 :(

**Comment by b1g334** [comment]
![virtualbox_cuckoo1_04_04_2016_16_08_33](https://cloud.githubusercontent.com/assets/18269162/14266782/a01cabc2-fa7f-11e5-86f3-96c4f0db150d.png)

**Comment by b1g334** [comment]
So... nuke and pave the ubuntu install.
Fresh install.
all updates & upgrades.
purge network manager, manually create the /etc/network/interface file.
fresh install of Cuckoo,
Fresh install of Vbox 5.0
Fresh image creation of win7 64
Disable firewall, disable updates, disable UAC.
ping to 192.168.1.1
ping from host to 192.168.1.101
Installed python, installed PIL, started agent, took a snapshot,
Started Cuckoo, started rooter, submitted url...

Same thing. IE (not responding)

 :( What Am I doing wrong?

**Comment by b1g334** [comment]
Further investigation...

Created a 32bit win7, replicated all necessary settings and it works... ????

**Comment by jbremer** [comment]
It could be our instrumentation for Internet Explorer 8 on 64-bit Windows 7 is crashing / freezing your specific version. We should probably investigate this further at some point.

**Comment by fbusta** [comment]
exactly the same issue here. Using latest stable version of IE8 (8.0.7601.17514) on 64bit Win7 Enterprise SP1 (same thing happened in a previous setup with 64bit Win7 Ultimate SP1).

Any ideas what would be causing the crash ???

**Comment by jbremer** [comment]
It's most likely due to our Javascript-related hooks which misbehave on untested versions of the browser. I hope to address these issues soon.

**Comment by jbremer** [comment]
@b1g334 @fbusta Could you please try again with the latest monitoring DLLs that I've just pushed? Please also try with bove the `iexplore` monitoring mode (i.e., `--options mode=iexplore`) and without. With will enable the iexplore-specific hooks and without will do the usual API hooking (as you'd see with malware), which will give quite a lot of garbage as well.

**Comment by jbremer** [comment]
These issues (and possibly some others) should have been resolved. Did you guys have the time to test?

**Comment by fbusta** [comment]
sorry for such late reply, have been away for a while. I'll test it now and let you guys know how it goes. Thanks!

**Comment by McCurity** [comment]
I was having similar issues both on an IE8 and IE11 installed snapshots (still am to some extent but working through them).  I had the 64bit version of Python installed on the Windows VM.  I uninstalled and installed the 32bit version and both IEs are at least properly launching now.  Working my way through the various data\monitors now to hopefully find the right fit.

**Comment by jbremer** [comment]
Thanks @McCurity. Ultimately the `latest` monitor should work best, though. 64-bit or 32-bit Python shouldn't matter. Also try adding `mode=iexplore` to the analysis options to speed up and simplify the analysis process itself. Btw, 64-bit IE8 should definitely work, and I believe 32-bit IE8 should as well.
As for IE9/10/11 I unfortunately haven't put too much effort into it yet. Let me know if you have any feedback or questions.

**Comment by McCurity** [comment]
I'm attaching a few sets of analysis from a Win7SP1x64 (Enterprise) with IE8.0.7601.17514.  Each set was using a different monitor as identified in the zip file name: cf3b0957e39242885f7e5a7d6f49245b3a88a2fd being the most recent from the Community master branch and 14b2b875dbfa50d19f5967c4b150a7a2e9465e39 being the more recent in the 2.0-RC1 package.

(Analysis 1) Snapshot1:
Python 2.7.12 (64-bit)

(Analysis 2) IE8Updated:
w/ KB3124275 (last IE8 patch available Jan '16)
Python 2.7.12 (64-bit)

(Analysis 3) IE8wPython32:
w/ KB3124275 (last IE8 patch available Jan '16)
Python 2.7.12 (32-bit)

I had previously run through every monitor available using the unpatched IE8 and 64-bit Python, all of which failed in some instances because IE stopped responding.  Those results in their entirety have since been wiped so I can't provide them but as you can see there were similar results in Analysis 1 and 2 for the two sample monitors.  Once I downgraded to 32-bit Python on the guest I made some progress using the 2.0-RC-1 latest monitor (14b2b875dbfa50d19f5967c4b150a7a2e9465e39).

Tomorrow I'll be working through the other monitors and can update if I get any cleaner results.  Let me know if you want me to capture any other tests.

[IE8-14b2b875dbfa50d19f5967c4b150a7a2e9465e39.zip](https://github.com/cuckoosandbox/cuckoo/files/340623/IE8-14b2b875dbfa50d19f5967c4b150a7a2e9465e39.zip)
[IE8-cf3b0957e39242885f7e5a7d6f49245b3a88a2fd.zip](https://github.com/cuckoosandbox/cuckoo/files/340624/IE8-cf3b0957e39242885f7e5a7d6f49245b3a88a2fd.zip)

Thanks!!

**Comment by fbusta** [comment]
hi guys, I've tried to debug this issue for a while without much luck (yeah, it's still happening and it's the same issue reported on the cuckoo monitor n-26). I'm super keen to get this fixed but I'd need some guidance on how to debug it and test it properly. Any ideas/links/references that I can use ??

**Comment by hexlax** [comment]
For a temporary workaround, I have noticed that when I disable "No Injection" that the analysis performs as expected..

**Comment by alabiana** [comment]
I have the same issue. If submit samples there is no internet connection. If i start the vm manually everything works fine.
also if i tick the "No Injection" checkbox

**Comment by jbremer** [comment]
Sorry for the inconvenience here guys. This is still a todo item for us but requires quite a bit of work and resources from our side.

**Comment by fbusta** [comment]
hey  @jbremer  no worries. I'm happy to help if you can point me to an easy way of debugging this issue.

**Comment by jbremer** [comment]
I have some news on this front! Yesterday I pushed out some new monitoring binaries.
Namely this one (in latest `master` branch of community) https://github.com/cuckoosandbox/community/commit/5dc6af4b1b5752906e9fc12244b01601a3350d66, this is basically the last version of monitor that was in-use including a patch to work properly under IE8/IE11.
And also this development monitor, which is more recent and as such has more features, but still needs some additional testing before official release (it also has IE8/IE11-related patches) https://github.com/cuckoosandbox/community/commit/43790ee2d76d501e0d5804fa764505e34f25d77d.
Upgrading can be done as follows, for both versions respectively:
`./utils/community.py -waf` ("stable" version)
`./utils/community.py -wafb monitor-33678c` ("development" version)

Please let me know if you have any feedback!

**Comment by jbremer** [comment]
Closing this issue as I didn't hear back after my update above and this should be working now.

**Comment by dunlaps** [comment]
i'm still having issues with IE11. I'm on cuckoo 2.0.4. VM is win7x64-sp1 with IE11.0.9600.17843. The process crashes soon after launch. So whether you launch it with a bat file: start http://www.msn.com or submit a URL for analysis, it crashes.  Also, if i turn off process injection, the problem goes away.
