### ISSUE TITLE
Cuckoo not executing (doc/xls/pdf) scripts

### ISSUE THREAD

**Issue by theproxima** [cuckoosandbox/cuckoo#853]
Ran into an issue after upgrading to rc1 that my vm's will no longer execute the doc/xls or pdf scripts.  It will read the documents and display the text in strings but it doesn't open the appropriate apps and execute the code within.   Any ideas?

**Comment by jbremer** [comment]
That's quite odd. Can you share some `analysis.log`'s and perhaps some more info on your setup?

**Comment by gregcopenhaver** [comment]
Hi,

I'm running into what may be the same issue.  This is new cuckoo & VM install and I've only run PE32, Javascript, and Word files so far, but the problem only occurs with the Word files.

Host machine:
CentOS 7 64-bit

Cuckoo:
Version 2.0-dev (commit eabc926596f558249dea843745e9c16a6d9085f4) with minor modifications to utils/rooter.py to work with openvpn using systemd (so should not be relevant to this issue), plus one change mentioned below

Machinery:
KVM

Guest Windows VM:
Windows 7 SP1 64-bit
Python 2.7.11 64-bit
Office 2016 32-bit (perhaps the problem is related to this being 32-bit?)

I updated analyzer/windows/modules/packages/doc.py to include the following line so it could find Word 2016:

`        ("ProgramFiles", "Microsoft Office", "root", "Office16", "WINWORD.EXE"),`

Here is a copy of analysis.log, which shows that pid 2620 was created and then terminated within a second:

`2016-04-13 10:51:55,000 [analyzer] DEBUG: Starting analyzer from: C:\rcjcibyfrg
2016-04-13 10:51:55,015 [analyzer] DEBUG: Pipe server name: \\.\PIPE\OdYUqZfihbbCMmxxzoooynGuAs
2016-04-13 10:51:55,015 [analyzer] DEBUG: Log pipe server name: \\.\PIPE\umDPrCggXxRPuSacbebwYyNTWWfvXK
2016-04-13 10:51:55,015 [analyzer] DEBUG: No analysis package specified, trying to detect it automagically.
2016-04-13 10:51:55,015 [analyzer] INFO: Automatically selected analysis package "doc"
2016-04-13 10:51:55,390 [analyzer] DEBUG: Started auxiliary module Disguise
2016-04-13 10:51:55,562 [analyzer] DEBUG: Loaded monitor into process with pid 480
2016-04-13 10:51:55,562 [analyzer] DEBUG: Started auxiliary module DumpTLSMasterSecrets
2016-04-13 10:51:55,562 [analyzer] DEBUG: Started auxiliary module Human
2016-04-13 10:51:55,562 [analyzer] DEBUG: Started auxiliary module InstallCertificate
2016-04-13 10:51:55,562 [analyzer] DEBUG: Started auxiliary module Screenshots
2016-04-13 10:51:55,592 [lib.api.process] INFO: Successfully executed process from path 'C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\WINWORD.EXE' with arguments [u'C:\\Users\\username\\AppData\\Local\\Temp\\due #57953895.doc'] and pid 2620
2016-04-13 10:51:56,592 [analyzer] INFO: Process with pid 2620 has terminated
2016-04-13 10:51:56,592 [analyzer] INFO: Process list is empty, terminating analysis.
2016-04-13 10:51:57,592 [analyzer] INFO: Analysis completed.`

If I'm able to get a 64-bit version of Office installed instead, I'll update you on whether or not the same thing happens, or something else.

Let me know if any other information would be helpful.

Thanks,

Greg

**Comment by jbremer** [comment]
Can you share the behavioral data perhaps? :)

**Comment by gregcopenhaver** [comment]
Unfortunately no behavioral data is created.  No networking data, either.  Only static analysis provides any information.  I exported the complete analysis and am attaching it here.  Since it contains the sample, I set the zip password to "infected".
[99.zip](https://github.com/cuckoosandbox/cuckoo/files/217524/99.zip)

**Comment by gregcopenhaver** [comment]
It looks like the same thing is happening with 64-bit Office 2016 as well.  I'm attaching the exported analysis for this one as well.
[101.zip](https://github.com/cuckoosandbox/cuckoo/files/217593/101.zip)

Let me know if there is anything else I can do to help.

Thanks,

Greg

**Comment by jbremer** [comment]
Given this works on Office versions we've tested, a copy of your version of Office would probably help, if that's possible.

**Comment by gregcopenhaver** [comment]
Unfortunately we're not able to provide you with a copy.  However, it was purchased from Microsoft's website this week and installed via the installer downloaded from their site.  The specific version of Word (as shown in About Word) is:

Microsoft Word 2016 MSO (16.0.6729.1014) 64-bit

**Comment by jbremer** [comment]
That's what I figured. Thanks for the version number, though.

**Comment by gregcopenhaver** [comment]
I found that when I disable injection (free=yes), Word 2016 will run and stay open and the analysis will continue until the timeout.  I used the latest commit in the monitor project, compiled with DEBUG=1.  This did cause a file to be created during the analysis, but it said nothing more than the following two lines repeated over and over again:

`Entered PRF
Leaving PRF`

There are still no dropped files when injection is enabled.

I experimented with manually running inject-x64.exe from the command line in the VM using the same arguments used by lib.api.process.Process#execute (I added some logging to see these).  I added some logging to see what is put into the config file that is passed via the --config argument and copied that data verbatim (since I'm not yet familiar with the options in that file). inject-x64.exe would exit almost immediately (I'm guessing it's supposed to, but I'm not sure), and Word would be started, but it did not display anything.

I watched this in Procmon to see if the Word PID changed after inject-x64.exe exited, but the PID remained the same.  I also confirmed that monitor-x64.dll was listed as one of the DLLs loaded in that process.  Other than the window not displaying, it seems that maybe it was working as expected.

Any thoughts on what else I might be able to try, or what sort of data (and how to get it) that might be useful to pinpoint the issue?

Thanks.

**Comment by toonswyzen** [comment]
I am having the same problem here, using Office 2013.

**Comment by jbremer** [comment]
Thanks for the in-depth analysis @gregcopenhaver. I'll provide you with a possible workaround either today or tomorrow. Let's try that hoping that that will solve some immediate issues (i.e., not being able to analyze Office documents at all).

Thanks for reporting these issues all!

**Comment by jbremer** [comment]
@gregcopenhaver @toonswyzen @theproxima I've just released a new monitor which fixes a memory corruption that might have played a role here, thanks to @knifeyspoony. See also https://github.com/cuckoosandbox/monitor/issues/21 https://github.com/cuckoosandbox/monitor/commit/df40a9acd421568461bbe23191883da56942b8fc. Please let me know if your issues still persist after this update.
(Do note that this is not actually the workaround that I mentioned - that is still to come, assuming this didn't fix your crashes).

**Comment by gregcopenhaver** [comment]
Thanks @jbremer for working on this.  Unfortunately the updates to https://github.com/cuckoosandbox/monitor/commit/df40a9acd421568461bbe23191883da56942b8fc did not resolve the issue.

I setup a snapshot with procmon.exe running to see if I could get more information about what's happening.  Here's a brief summary of what I see happening (I can try to get more details for you if needed).

Word is started.
Immediately after that, a thread in Word is created (ID 1820).
Word does some registry queries and loads a couple DLLs.
inject-x64.exe then exits with status 0
Word then goes on to do a lot more registry and filesystem activity, loading many more DLLs
Word then finally loads monitor-x64.dll
Word accesses a few more Word/Office files/directories
Word then reads C:\cuckoo_2104.ini
Word then reads C:\Program Files\Common Files\Microsoft Shared\ClickToRun\AppvIsvSubsystems64.dll
Thread 1820 then exits with status 0
The stack at the Thread exit event has monitor_unhook + 0x216 on top, which is address 0x65a817ff, which according to objdump is the address of _ldr_dll_notification
This is the last time anything shows up from monitor-x64.dll in procmon.exe
Word then does a bunch of QueryNameInformationFile events for various .dll files
Word then exits with a status of -1073741819 (0xc0000005, apparently a very common error code for Office when non-Office DLLs are involved).

I hope to have time to setup a snapshot with a debugger, so I can use that to get more detailed information and pinpoint where the problem is happening, if you or someone else hasn't found/fixed it by then.

Thanks for your help!

Greg

**Comment by jbremer** [comment]
The fact that it crashes (most likely) at `_ldr_dll_notification` is quite interesting. That could definitely be the culprit. I'll provide you with a version ASAP that might help us debug this issue further.

**Comment by jbremer** [comment]
@gregcopenhaver Could you please try one or two runs with the following DLLs?
http://cuckoo.sh/ba6bda9b959ed696/dllnotifydbg.tar.gz
Please share the monitor debug logs - thanks!

**Comment by gregcopenhaver** [comment]
Thanks @jbremer 

Unfortunately the only monitor debug file that's dropped is still completely empty when injection is enabled.

**Comment by theproxima** [comment]
any update on this issue?

**Comment by jbremer** [comment]
As I don't have Office 2013 or Office 2016 at hand I can't do much testing with those versions currently.. Following are monitor binaries without the `DLL Load Notification` part - the code that may have caused crashes pointed out by @gregcopenhaver. Could you please re-test with these DLLs and post some results? Thanks.

http://cuckoo.sh/0fefe3a2d81baefe/monitor.tgz

**Comment by gregcopenhaver** [comment]
Thanks @jbremer.  Sorry, I didn't notice your update until now.  I tried the monitor binaries without the DLL Load Notification part.  Word 2016 no longer crashes, but I get zero behavioral information, and no dropped files.  The analysis log shows an error when trying to upload a file to the host (perhaps that is the monitor-debug file?):

2016-05-06 07:00:34,015 [analyzer] DEBUG: Starting analyzer from: C:\uwguwohixx
2016-05-06 07:00:34,015 [analyzer] DEBUG: Pipe server name: \\.\PIPE\xrytQzAaQlWWHGJNDvzFBCLJYHI
2016-05-06 07:00:34,015 [analyzer] DEBUG: Log pipe server name: \\.\PIPE\xgXiYTFhKnkrlOMiICAdRi
2016-05-06 07:00:34,015 [analyzer] DEBUG: No analysis package specified, trying to detect it automagically.
2016-05-06 07:00:34,015 [analyzer] INFO: Automatically selected analysis package "doc"
2016-05-06 07:00:34,405 [analyzer] DEBUG: Started auxiliary module Disguise
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: shutdown-mutex=Global\agRSXL
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: track=0
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: analyzer=C:\uwguwohixx
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: disguise=0
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: logpipe=\\.\PIPE\xgXiYTFhKnkrlOMiICAdRi
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: startup-time=16800000
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: pipe-pid=1
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: pipe=\\.\PIPE\xrytQzAaQlWWHGJNDvzFBCLJYHI
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: force-sleepskip=0
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: mode=dumptls
2016-05-06 07:00:34,437 [lib.api.process] DEBUG: Injection config: first-process=1
2016-05-06 07:00:34,592 [analyzer] DEBUG: Loaded monitor into process with pid 484
2016-05-06 07:00:34,592 [analyzer] DEBUG: Started auxiliary module DumpTLSMasterSecrets
2016-05-06 07:00:34,592 [analyzer] DEBUG: Started auxiliary module Human
2016-05-06 07:00:34,592 [analyzer] DEBUG: Started auxiliary module InstallCertificate
2016-05-06 07:00:34,592 [analyzer] DEBUG: Started auxiliary module Screenshots
2016-05-06 07:00:34,592 [lib.api.process] DEBUG: Injection config: shutdown-mutex=Global\agRSXL
2016-05-06 07:00:34,592 [lib.api.process] DEBUG: Injection config: track=1
2016-05-06 07:00:34,592 [lib.api.process] DEBUG: Injection config: analyzer=C:\uwguwohixx
2016-05-06 07:00:34,592 [lib.api.process] DEBUG: Injection config: disguise=0
2016-05-06 07:00:34,592 [lib.api.process] DEBUG: Injection config: logpipe=\\.\PIPE\xgXiYTFhKnkrlOMiICAdRi
2016-05-06 07:00:34,592 [lib.api.process] DEBUG: Injection config: startup-time=16800000
2016-05-06 07:00:34,608 [lib.api.process] DEBUG: Injection config: pipe-pid=1
2016-05-06 07:00:34,608 [lib.api.process] DEBUG: Injection config: pipe=\\.\PIPE\xrytQzAaQlWWHGJNDvzFBCLJYHI
2016-05-06 07:00:34,608 [lib.api.process] DEBUG: Injection config: force-sleepskip=0
2016-05-06 07:00:34,608 [lib.api.process] DEBUG: Injection config: mode=
2016-05-06 07:00:34,608 [lib.api.process] DEBUG: Injection config: first-process=0
2016-05-06 07:00:34,608 [lib.api.process] DEBUG: Executing process from path 'C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\WINWORD.EXE' with arguments ['bin\\inject-x86.exe', '--app', u'C:\\PROGRA~2\\MICROS~1\\root\\Office16\\WINWORD.EXE', '--args', u'C:\\Users\\User\\AppData\\Local\\Temp\\id_card_823597.rtf', '--apc', '--dll', 'C:\\uwguwohixx\\bin\\monitor-x86.dll', '--config', 'c:\\users\\User\\appdata\\local\\temp\\tmpwfztjt', '--curdir', u'C:\\Users\\User\\AppData\\Local\\Temp']
2016-05-06 07:00:34,640 [lib.api.process] INFO: Successfully executed process from path 'C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\WINWORD.EXE' with arguments [u'C:\\Users\\User\\AppData\\Local\\Temp\\id_card_823597.rtf'] and pid 2296
2016-05-06 07:01:11,842 [modules.auxiliary.human] INFO: Found button "OK", clicking it
2016-05-06 07:02:34,828 [analyzer] INFO: Analysis timeout hit, terminating analysis.
**2016-05-06 07:02:40,921 [lib.common.results] ERROR: Exception uploading file c:\users\User\appdata\local\temp\tmpz7rbub to host: [Errno 9] Bad file descriptor**
2016-05-06 07:02:40,953 [lib.api.process] INFO: Memory dump of process with pid 2296 completed
2016-05-06 07:02:40,953 [analyzer] INFO: Analysis completed.

**Comment by gregcopenhaver** [comment]
Office 2016 32-bit has been working great since monitor commit https://github.com/cuckoosandbox/monitor/commit/275be6160613419a110c29b4120ff7d82da9c481 (especially when the option "mode=office" option is used).  64-bit Office 2016 still crashes, however.

A few questions:
Are these "mode=" options documented anywhere?  I haven't found anything, though maybe I haven't looked hard enough.
What does "mode=office" do differently as compared to no mode being specified?
Is there a simple way to ensure that "mode=office" is automatically used as an option when Office is used as part of the analysis?

Thanks for fixing this on 32-bit Office!  It's been very nice being able to run Office files in our own cuckoo sandbox.

**Comment by jbremer** [comment]
Sorry for the delay in answering, @gregcopenhaver, I believe the issue is a similar one to that of the 32-bit Office 2016, but it has to be *fixed* in a slightly different way. I haven't had time for that yet.
Btw, any reason why you'd prefer to use 64-bit Office over 32-bit?

**Comment by gregcopenhaver** [comment]
Sorry to respond so long after your update.  Actually I do not have any particular reason to use 64-bit Office over 32-bit.  32-bit is working fine for us, and that's probably good enough for now.  If I come across anything malicious that's specific to 64-bit Office, I'll let you guys know.

Thanks again!

**Comment by irishhuggiebear** [comment]
Hi All,

So can you run password protected files e.g .doc through Cuckoo for testing? Am i correct in saying from your posts that 32bit version of Office works? I would really appreciate what version of Cuckoo is required and any steps or plugins i require to do this, thank you.

Huggie

**Comment by zashraf1337** [comment]
we can also integrate this https://github.com/nolze/ms-offcrypto-tool

**Comment by jbremer** [comment]
I already integrated their research with `sflock`, see also https://github.com/jbremer/sflock/commit/3f6a96abe1dbb4405e4fb7fd0d16863f634b09fb, but the finishing touch, i.e., handling the passwords throughout Cuckoo and decrypting the Office files when necessary, is actually the most work here.
So that's still on the todo list.

**Comment by Clevero** [comment]
I'm currently testing in Windows 7 32 Bit SP1 with Office 2016 (O365) and I'm not able to run Word documents (others not tested) unless I disable injection.

Office 365 MSO (16.0.10730.20102)

I've installed Office 2010 and it's working.

**Comment by kapils1234** [comment]
> disable injection (free=yes)

Hi,
I have applied the patch to my cuckoo environment facing similar issue.Right now I didn't get the behavioral data from cuckoo worker.
Could you provide a detailed steps to set disable injection (free=yes) in cuckoo controller vm?

**Comment by kapils1234** [comment]
> I found that when I disable injection (free=yes), Word 2016 will run and stay open and the analysis will continue until the timeout. I used the latest commit in the monitor project, compiled with DEBUG=1. This did cause a file to be created during the analysis, but it said nothing more than the following two lines repeated over and over again:
> 
> > Entered PRF
> > Leaving PRF
> 
> There are still no dropped files when injection is enabled.
> 
> I experimented with manually running inject-x64.exe from the command line in the VM using the same arguments used by lib.api.process.Process#execute (I added some logging to see these). I added some logging to see what is put into the config file that is passed via the --config argument and copied that data verbatim (since I'm not yet familiar with the options in that file). inject-x64.exe would exit almost immediately (I'm guessing it's supposed to, but I'm not sure), and Word would be started, but it did not display anything.
> 
> I watched this in Procmon (edit) Process Explorer to see if the Word PID changed after inject-x64.exe exited, but the PID remained the same. I also confirmed that monitor-x64.dll was listed as one of the DLLs loaded in that process. Other than the window not displaying, it seems that maybe it was working as expected.
> 
> Any thoughts on what else I might be able to try, or what sort of data (and how to get it) that might be useful to pinpoint the issue?
> 
> Thanks.



> I found that when I disable injection (free=yes), Word 2016 will run and stay open and the analysis will continue until the timeout. I used the latest commit in the monitor project, compiled with DEBUG=1. This did cause a file to be created during the analysis, but it said nothing more than the following two lines repeated over and over again:
> 
> > Entered PRF
> > Leaving PRF
> 
> There are still no dropped files when injection is enabled.
> 
> I experimented with manually running inject-x64.exe from the command line in the VM using the same arguments used by lib.api.process.Process#execute (I added some logging to see these). I added some logging to see what is put into the config file that is passed via the --config argument and copied that data verbatim (since I'm not yet familiar with the options in that file). inject-x64.exe would exit almost immediately (I'm guessing it's supposed to, but I'm not sure), and Word would be started, but it did not display anything.
> 
> I watched this in Procmon (edit) Process Explorer to see if the Word PID changed after inject-x64.exe exited, but the PID remained the same. I also confirmed that monitor-x64.dll was listed as one of the DLLs loaded in that process. Other than the window not displaying, it seems that maybe it was working as expected.
> 
> Any thoughts on what else I might be able to try, or what sort of data (and how to get it) that might be useful to pinpoint the issue?
> 
> Thanks.

Hi,
I have applied the patch to my cuckoo environment facing similar issue.Right now I didn't get the behavioral data from cuckoo worker.
Could you provide a detailed steps to set disable injection (free=yes) in cuckoo controller vm?

**Comment by kapils1234** [comment]
> > I found that when I disable injection (free=yes), Word 2016 will run and stay open and the analysis will continue until the timeout. I used the latest commit in the monitor project, compiled with DEBUG=1. This did cause a file to be created during the analysis, but it said nothing more than the following two lines repeated over and over again:
> > > Entered PRF
> > > Leaving PRF
> > 
> > 
> > There are still no dropped files when injection is enabled.
> > I experimented with manually running inject-x64.exe from the command line in the VM using the same arguments used by lib.api.process.Process#execute (I added some logging to see these). I added some logging to see what is put into the config file that is passed via the --config argument and copied that data verbatim (since I'm not yet familiar with the options in that file). inject-x64.exe would exit almost immediately (I'm guessing it's supposed to, but I'm not sure), and Word would be started, but it did not display anything.
> > I watched this in Procmon (edit) Process Explorer to see if the Word PID changed after inject-x64.exe exited, but the PID remained the same. I also confirmed that monitor-x64.dll was listed as one of the DLLs loaded in that process. Other than the window not displaying, it seems that maybe it was working as expected.
> > Any thoughts on what else I might be able to try, or what sort of data (and how to get it) that might be useful to pinpoint the issue?
> > Thanks.
> 
> > I found that when I disable injection (free=yes), Word 2016 will run and stay open and the analysis will continue until the timeout. I used the latest commit in the monitor project, compiled with DEBUG=1. This did cause a file to be created during the analysis, but it said nothing more than the following two lines repeated over and over again:
> > > Entered PRF
> > > Leaving PRF
> > 
> > 
> > There are still no dropped files when injection is enabled.
> > I experimented with manually running inject-x64.exe from the command line in the VM using the same arguments used by lib.api.process.Process#execute (I added some logging to see these). I added some logging to see what is put into the config file that is passed via the --config argument and copied that data verbatim (since I'm not yet familiar with the options in that file). inject-x64.exe would exit almost immediately (I'm guessing it's supposed to, but I'm not sure), and Word would be started, but it did not display anything.
> > I watched this in Procmon (edit) Process Explorer to see if the Word PID changed after inject-x64.exe exited, but the PID remained the same. I also confirmed that monitor-x64.dll was listed as one of the DLLs loaded in that process. Other than the window not displaying, it seems that maybe it was working as expected.
> > Any thoughts on what else I might be able to try, or what sort of data (and how to get it) that might be useful to pinpoint the issue?
> > Thanks.
> 
> Hi,
> I have applied the patch to my cuckoo environment facing similar issue.Right now I didn't get the behavioral data from cuckoo worker.
> Could you provide a detailed steps to set disable injection (free=yes) in cuckoo controller vm for Centos?

Any update on my query please?

**Comment by stoerchl** [comment]
Is there an update on behavior analysis with 32bit Office 2016? it still crashes..

**Comment by RicoVZ** [comment]
Hi @kapils1234 ,

`free=yes` is an analysis option. It should be provided when submitting a file/url. A command line examples would be:

`$ cuckoo submit /tmp/example.doc --options "free=yes"`

**Comment by Yasir87** [comment]
Since i am new to programming,i am unable to execute power shell scripting on cuckoo, how to enable it.

**Comment by Yasir87** [comment]
![image](https://user-images.githubusercontent.com/57381130/68175320-d8e43800-ffa6-11e9-8495-c8fee3e5f4e8.png)
